spring:
  application:
    name: entitlements
server:
  port: 9095

keycloak:
  server-url: http://keycloak
  realm: entlrealm
  client-id: entl-client
  clientSecret: yl47n5AQsGGlVKsFYJ2sjJlJ9gKzW5AS