version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
    command: start --optimized --import-realm
    ports:
      - "8085:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak/entlrealm-export.json:/opt/keycloak/data/import/entlrealm-export.json:ro
      # Custom theme
      - /Users/test/Documents/LextrDocker/my-keycloak-app/myapp-theme:/opt/keycloak/themes/myapp-theme

# below volumes are for persisting data
volumes:
  postgres_data:


# Note: Configuration can be externalized using .env file or Docker secrets for better security.
# Example .env file content:
# POSTGRES_DB=keycloak
# POSTGRES_USER=keycloak
# POSTGRES_PASSWORD=password
# KEYCLOAK_ADMIN=admin
# KEYCLOAK_ADMIN_PASSWORD=admin
# KC_DB_USERNAME=keycloak
# KC_DB_PASSWORD=password
# KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak

#Multiple environment files can be used for different environments like development, staging, and production.
# Example:
# docker-compose -f docker-compose.yml --env-file .env.dev up
# docker-compose -f docker-compose.yml --env-file .env.prod up -d
