apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
type: Opaque
data:
  POSTGRES_DB: a2V5Y2xvYWNr      # base64 of 'keycloak'
  POSTGRES_USER: a2V5Y2xvYWNr    # base64 of 'keycloak'
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64 of 'password'
  KEYCLOAK_ADMIN: YWRtaW4        # base64 of 'admin'
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4 # base64 of 'admin'
